### ISSUE TITLE
Excerpt's HTML tags are stripped if more tag in post

### ISSUE THREAD

**Issue by RogerAndersson** [picandocodigo/List-Category-Posts#181]
I want to show a list of posts for a specific category. Each entry shall contain a thumbnail, the post content until more tag with html tags included.

I am using the following catlist config
[catlist name=aktuellt orderby=modified order=desc numberposts=-1 thumbnail=yes thumbnail_size=300,300 thumbnail_class=lcp_thumbnail date=yes excerpt=full excerpt_size=300 excerpt_strip=no template=widget-template]

Posts without more tag are shown correct. The content contains html tags.

But posts which has a more tags are stripped on html tags.

**Comment by AlfredJKwack** [comment]
Hi there, 
Have you tried excerpt_overwrite? The documentation states:

> If you want to overwrite the post's separate excerpt with an automatically generated one (may be useful to allow HTML tags), use excerpt_overwrite=yes

I believe that _separate excerpt_ and content with a __ are handled the same way.

**Comment by RogerAndersson** [comment]
Yes, I have tried with excerpt_overwrite=yes, but it makes no difference.

Currently I am using
[catlist name=aktuellt orderby=date order=desc numberposts=-1 thumbnail=yes thumbnail_size=300,300 thumbnail_class=lcp_thumbnail date=yes date_modified=no excerpt=full excerpt_overwrite=yes excerpt_size=300 excerpt_strip=no template=widget-template]

**Comment by zymeth25** [comment]
Solution:
* Use the shortcode shared in the first comment
* In post editor click 'Screen options' and make sure the 'Excerpt' checkbox is checked
* Instead of using the more tag, put the excerpt in the 'Excerpt' meta box, you only need to do this for posts where you previously used the more tag, you don't have to change other posts.

Result: html tags are not stripped in any excerpts, whether auto generated by the plugin or taken from the 'Excerpt' meta box.

issue can be closed I think.
