### ISSUE TITLE
How can I display the lists without bullets?

### ISSUE THREAD

**Issue by StanleyKnife** [picandocodigo/List-Category-Posts#212]
Also, I'd like to be able to have them centered...

Thank you!

**Comment by Sophist-UK** [comment]
CSS

**Comment by StanleyKnife** [comment]
Yes, I know. But can you tell me what to do?

**Comment by Sophist-UK** [comment]
Open the list in your browser. View source. Add appropriate CSS to define the list as bulleted and list items centred.

**Comment by StanleyKnife** [comment]
I want to remove the bullets, not add them... and I know very little CSS. Are you able just to tell me the CSS to add? I realise it must be frustrating dealing with a newbie.

**Comment by Sophist-UK** [comment]
No - that is not it at all.

It's frustrating dealing with someone who can't be bothered to go out on the internet and try to learn what they need to know, and so asks for help every time they need to do something.

"Give a man a fish and he is fed for a day - force him to go out and learn to fish and he can feed himself for ever"

Go out and try to learn what you need. Try to fix it. Try again if you still can't do it. Then try again. And if you are still stuck on the fine detail, come back and ask a much more specific question.

**Comment by StanleyKnife** [comment]
And that's exactly what I did.

Well, thanks for refusing to help. I won't bother you again.

**Comment by Sophist-UK** [comment]
You have never given any indication that you have researched or tried. "How do I do it?" is not exactly a specific question.

If you had posted the current HTML here (or given a link) and said that you had "tried x, y and z but none of them worked, though when you did x it was half way there", then I might have some indication that you  had tried to do something yourself.

But "Please help me fix it, but I am not going to give you any more details about the specifics of my problem" is never going to get you an answer from anyone.

**Comment by Sophist-UK** [comment]
P.S. You might get a better response if you bothered to find out what the proper support page for the plugin is and posted your question there.

**Comment by StanleyKnife** [comment]
OK, here's the thing. I'm not a web coder. Never needed to be, never wanted to be. But I am putting together a website, and needed a little help with a plugin - all I wanted was for someone to tell me the code to type in.

I'm an expert Photoshop user. I've written books about it. I answer a lot of questions on Quora from people asking about basic issues, because they need help and I'm willing to point them in the right direction. 

If you aren't willing to help, and you clearly aren't, then I don't understand why you engaged with my question in the first place.

**Comment by Sophist-UK** [comment]
Ok, here's the thing (correcting all the misconceptions you have just stated)...

If you want to put together a web site, then unless the defaults are exactly what you want - or you are prepared to live with them, then you need some web skills to some degree at least.

And if you want help for a plugin you should ask for help on the correct web page for support for that plugin - and this is not it. From this web page you can reach the correct page for support in three clicks.

There is no one set of code to type in - it depends on what you have put in your shortcode, and where the shortcode appears on your wordpress page and on the template you are using and probably several other things. So unless you give more information no one will be able to help you.

The fact that you are "an expert Photoshop user" and have "written books about it" doesn't entitle you to expect other people to do your work for you in other technical areas. And if you are clever enough to have done those things, then it seems reasonable to assume that you are clever enough to learn a bit of CSS in order to fix your own problem.

And despite what you might think, **I AM HELPING YOU**. I am helping you to learn to be more self sufficient. I am helping you to understand what you need to do for yourself and what information you need to provide before other people can help you, and to learn to ask your questions in the right place. And I have pointed you in the right direction several times already. It's not my fault if you are too arrogant to listen, and arrogantly believe that (because you are an expert in another field) other people are there to do your work for you because doing it yourself is now beneath you.

To put this in simple terms you might understand, if I posted a question on the Photoshop plugins coding site about wanting help to use Photoshop to fix up a picture which is the wrong colour, could you immediately give me an answer? No - you might well say I should use the correct user forum to ask the question and that people would need more information about exactly what the colour problem was before they could help you. And you might ask if they had read the manual or looked on the web or ask what they had already tried. 

And now I am going to disengage - because I have given you much more help than you deserve.

**Comment by StanleyKnife** [comment]
"In three clicks". Yes. Of course, you could just give me the address of the correct web page.

**Comment by Sophist-UK** [comment]
Yes - I could. or you could go and find it for yourself. But apparently that is also too much for you. 

Says it all really.

**Comment by StanleyKnife** [comment]
You're right, it is too much for me. That's why I asked for help.

**Comment by Sophist-UK** [comment]
Best to give up on your web site then I guess.

**Comment by StanleyKnife** [comment]
That's not quite the case. I've put a lot of effort into this site, and at this point I got stuck. So I asked for help. I'll look elsewhere.

**Comment by Sophist-UK** [comment]
No one said you didn't put effort into your site. I said that you put no effort into solving this problem. You couldn't even be bothered to include the information necessary for someone to help you. All you have done is gripe about how I am being unhelpful.

**Comment by Sophist-UK** [comment]
And to reiterate - the solution is not difficult.

You need to add CSS. But I cannot tell you what that CSS needs to be because you have not given enough detail for anyone to be able to work it out for you. 

Fixing it yourself is not difficult. There are numerous web sites which give examples that you can tweak.

Or you could ask on the correct support page for the plugin and someone else will either give you generic help that you could find for yourself on the web and you will still have to tweak it, or they will tell you as I have that you need to provide more information if you want an answer.

**Comment by Sophist-UK** [comment]
If you want it spoon fed to you, run a google search for "HTML unordered list remove bullets" and you will get the simple instruction in enlarged font as the first organic result (of 35,000 web pages which explain this).

**Comment by StanleyKnife** [comment]
Thank you.

**Comment by vr-gallagher** [comment]
If you right click on the list and click inspect element, you'll find the plugin assigns a css class of "lcp_catlist" to the unordered list:

`<ul class="lcp_catlist" id="lcp_instance_0">` 

So you just need add css to that class in your stylesheet:

`
ul.lcp_catlist > li {
    list-style-type: none;    /* removes disks */
}

ul.lcp_catlist {
    margin-left: 40px;  /* removes indentation */
}
`

For the `ul.lcp_catlist > li`, that simply says that for any **u**nordered **l**ist with the class of "lcp_catlist" select the **l**ist **i**tems that comes after it and run the following css. 

you may need to add "!important" if the css isn't working—not best practice but sometimes it's required to override plugins. if you are using ordered lists you would need to replace the "ul" with "ol"

**Comment by picandocodigo** [comment]
This has also been answered on the [FAQ](https://github.com/picandocodigo/List-Category-Posts/blob/master/doc/FAQ.md#bullets).

**Comment by zymeth25** [comment]
Can be closed, amusing to read though 😃

**Comment by psygo** [comment]
One hack you could use is leverage Github's existing styling, so, in your markdown:

```html
<div id="user-content-toc">
  <ul>
    ...
  </ul>
</div>
```
