### ISSUE TITLE
Improvement: Subheadlines for alphabetical ordering

### ISSUE THREAD

**Issue by julia-r** [picandocodigo/List-Category-Posts#222]
I am ordering posts alphabetically by title and it would be cool to have subheadlines in between, to indicate that titles starting with a new letter are now listed. Example:

> **A**
> Apple
> **B**
> Banana
> **P**
> Peach
> Pineapple 

Those Subheadlines could have anchor elements, so they could be used to jump to a certain letter.

**Comment by zymeth25** [comment]
Would be cool, but would also require quite a lot of code to be added. Not sure we should include it in the plugin.

**Comment by zymeth25** [comment]
I created a simple template implementing this some time ago.

https://gist.github.com/zymeth25/e46ae830e42fb7a200306cfaa87ba18a

Issue can be closed I think.

**Comment by picandocodigo** [comment]
@zymeth25 Do you think we should have some more examples in the templates directory and your gist could be one of them?

**Comment by zymeth25** [comment]
@picandocodigo Why not? But generally what people are looking for are things that need 1-4 lines of template code. So things like this gist we can put in the template directory because it changes a lot of the default template. Smaller examples we can put in a "Template how to" which can be either in the template directory or in the wiki.

There are many useful examples on the support forum already so we have material for this.
