### ISSUE TITLE
Show date first, then the title of the post

### ISSUE THREAD

**Issue by wlam69** [picandocodigo/List-Category-Posts#226]
I was wondering if it is generally possible to show the date before (left to) the title of the post. As I want to use is globally on my web project, can you tell me please where to change it? Thanks!

Wolve

**Comment by vacuus** [comment]
Hmm this should be able to be done using CSS. I just checked though and there doesn't seem to be a way to select the date using CSS. The date should probably be wrapped in a span tag.

**Comment by wlam69** [comment]
No, I think it must be done in some php files of the plugin. Anyway thanks for answer

**Comment by wlam69** [comment]
anybody an idea? thanks for help!

**Comment by picandocodigo** [comment]
@wlam69 as @vacuus said, you can customize this with CSS. In your shortcode, you should set a class for your date (and optionally a tag):
`[catlist date=yes date_class="lcp_date"]`
Then in your CSS file add something like this to the lcp_date class:
```css
.lcp_date{
  float: left;
}
```
This will align the date to the left of the title. If you want to add a separator between the date and the title, you can use:
```css
.lcp_date:after{
  content: " - ";
  white-space: pre;
}
```

**Comment by everbeta** [comment]
@picandocodigo I need to show the date before the post title as well; the solution above works great on desktop view, but when I view my page on mobile (or scale my browser window so that the list item content breaks into multiple lines, the date no longer shows up first - it floats left on the next line down.  [here](http://everbeta.com/mather/news/press-releases-2017/) is an example page where I have the code in place. Is there a way to force the date to appear first, even when viewed on mobile (or when the list item breaks into multiple lines ? )

**Comment by everbeta** [comment]
After struggling to make a CSS solution work well, I was able to solve the issue by creating a custom php template for the plug-in: https://github.com/picandocodigo/List-Category-Posts/tree/master/templates

**Comment by picandocodigo** [comment]
The solution is either modifying the CSS or creating a new template for more specific positioning. Closing this issue for now.
