### ISSUE TITLE
Custom fields – different mix of criteria, orderby and display not possible

### ISSUE THREAD

**Issue by jensjakobsen** [picandocodigo/List-Category-Posts#261]
Hi

I want to mix:
customfield_name with customfield_display in the shortcode, like the example below:

[catlist name=”Rating” customfield_name=”Bryggeri” customfield_value=”Carlsberg” customfield_display=”Karakter” customfield_orderby=”Karakter” order=desc customfield_display_name=”no”]

Apparently there needs to be a consistency across the entire shortcode, meaning, if I start out with a customfield_name such as customfield_name=”Bryggeri”, I can’t mix it with e.g.: customfield_display=”Karakter”

Is that true?

**Comment by zymeth25** [comment]
@jensjakobsen No, that is not true. You should be able to select all posts that have specific `customfield_name` and `customfield_value`, and then to use `customfield_display` to select another field to be displayed. This is how the plugin works right now and it is possible to set it up like this:
```
[catlist name=”Rating” customfield_name=”Bryggeri” customfield_value=”Carlsberg” customfield_display=”Karakter” customfield_display_name=”no”]
```
This would work as intended, but notice that I omitted `customfield_orderby=”Karakter” order=desc`. The problem is it doesn't work when you use both `customfield_name` and `customfield_orderby` because the value of the latter overrides that of the former. This is how the plugin parses the parameters and feeds them to the `query_posts` function. So in your shortcode:
```
[catlist name=”Rating” customfield_name=”Bryggeri” customfield_value=”Carlsberg” customfield_display=”Karakter” customfield_orderby=”Karakter” order=desc customfield_display_name=”no”]
```
the plugin will display all posts with category "Rating" and a custom field called "Karakter" (not "Bryggeri" as you intended) with a value of "Carlsberg".

I think this should be mentioned in the docs, for now, but it can be fixed using [sub-meta queries](http://wordpress.stackexchange.com/a/246358/3687)

**Comment by jensjakobsen** [comment]
Thanks a lot! Appreciated.
