### ISSUE TITLE
[catlist categorypage="yes"] does not work since update to WordPress 4.9

### ISSUE THREAD

**Issue by helmutka** [picandocodigo/List-Category-Posts#263]
[catlist categorypage="yes"] now deliveres all posts and not only posts from the same category. This is since wordpress 4.9

**Comment by picandocodigo** [comment]
This was because the category check would compare a return value against the "Empty Term" translation key which was changed [in this commit](WordPress/WordPress@a42b9ce#diff-efd15818123d55a117706670be80c15aR749) adding periods at the end of some error messages. So it was just a matter of adding the period in the if condition.

Thanks @helmutka!

**Comment by helmutka** [comment]
Good job, thanks, it's working now.
