### ISSUE TITLE
Pagination not updating content

### ISSUE THREAD

**Issue by reddykvishal** [picandocodigo/List-Category-Posts#291]
I turned on pagination for a category using the following shortcode:

`[catlist id=4 thumbnail=yes thumbnail_class=cat_list_tn thumbnail_size=752,500 title_class=lcp_title pagination=yes ]`

It does show pagination controls but when I click on any page number, it scrolls to the top of the page and doesn't update content.

**Comment by zymeth25** [comment]
Hi @reddykvishal 

A similar problem was discussed in support forum [here](https://wordpress.org/support/topic/pagination-is-not-working-14/). It is most probably caused by JavaScript used by your WP theme. If you share a link to your site I can tell you for sure.

**Comment by reddykvishal** [comment]
Hi @zymeth25 

Thanks for figuring the problem. It can be found here: https://goo.gl/touXta

**Comment by zymeth25** [comment]
I examined the website you shared. The problem is indeed with the JavaScript belonging to the theme. When I load the website with JavaScript turned off pagination works without a problem. Let me know if it's possible to ask the theme author for support, if not I'll try to think of another solution for you.

**Comment by reddykvishal** [comment]
Unfortunately, there is no way to reach out to the theme developer. Can you give me any pointers to identify which library or part of script is interfering with this. 

Also, is it possible to just disable loading it using js, instead have them as hyperlinks leading to new page on click.

**Comment by zymeth25** [comment]
>have them as hyperlinks leading to new page on click.

The LCP plugin uses no JS at all. Normally, when you click a link, a HTTP request is performed.

The problem is in the theme's script that prevents the default behavior of pagination links and performs a scroll instead.

The script causing this problem is `http://bec.umich.edu/wp-content/themes/salient/js/init.js?ver=7.0.9`. There's an event listener on line 8723:
```javascript
$('body').on('click','#header-outer nav .sf-menu a, #footer-outer .nectar-button, .container-wrap a:not(.wpb_tabs_nav a):not(.woocommerce-tabs a), .swiper-slide .button a, #slide-out-widget-area a, #mobile-menu .container ul li a, #slide-out-widget-area .inner div a',function(e){
```

This is a pretty badly written jQuery event listener but what inerests us is this part: `.container-wrap a:not(.wpb_tabs_nav a):not(.woocommerce-tabs a)`, this is what 'catches' our pagination links and executes the function that follows (which adds the `animated-scrolling` class to `<body>` etc).

I don't think you should remove the whole `init.js` file because it has thousands of lines and it would probably break your theme. But if you are familiar with JS you can modify this file in your child theme.

**Comment by zymeth25** [comment]
Ok @reddykvishal , I tested your website and there's actually only one change you need to make. It's the beforementioned line 8723 of init.js. make sure it includes `:not(.lcp_paginator a)` just after `:not(.woocommerce-tabs a)` so that the entire line reads:

```javascript
$('body').on('click','#header-outer nav .sf-menu a, #footer-outer .nectar-button, .container-wrap a:not(.wpb_tabs_nav a):not(.woocommerce-tabs a):not(.lcp_paginator a), .swiper-slide .button a, #slide-out-widget-area a, #mobile-menu .container ul li a, #slide-out-widget-area .inner div a',function(e){
```
This solves the problem, nothing is broken and pagination works.
