### ISSUE TITLE
ordering on numbers doesn't work

### ISSUE THREAD

**Issue by ryuken** [picandocodigo/List-Category-Posts#314]
### Expected behavior
I expect the ordering to work when title starts with numbers:
1. sfjfnjfdg
2. gjfngjfng
3. nfgjfngj
..
12. jfnjfngj
..
20. fnjgnfg

### Actual behavior
1. sfjfnjfdg
12. jfnjfngj
2. gjfngjfng
20. fnjgnfg
3. nfgjfngj

### Shortcode used and steps to reproduce the behavior
I also tried with using a custom field with just the numbers.
It only works correct if i replace the numbers with a-z but that's not acceptable as you're limited with a-z.

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by ryuken** [comment]
yeah you have the following list:

1. Monkey
2. Cheese
3. Frog
..
10. Elvis

I expect that if I order this list that it should be order based on those numbers 1-10.

The order was:
1. Monkey
10. Elvis
2. Cheese
3. Frog

That didn't work, so I made a custom field and named it number with the correct numbers
so:
1. Monkey (customfield 1)
2. Cheese (customfield 2)
3. Frog (customfield 3)
..
10. Elvis (customfield 10)

This gave me the same order...
What does work, is if i use the following custom fields:
1. Monkey (customfield a)
2. Cheese (customfield b)
3. Frog (customfield c)
..
10. Elvis (customfield d)

So ordering works on letters, but not on numbers.

**Comment by zymeth25** [comment]
Ah, I see, this is because WP stores custom fields as strings and reads them as strings. Same goes for post titles. And as a rule a "10" string comes before a "3" string, contrary to what it would be if the fields were interpreted as integers.

The simplest workaround is described [here](https://wordpress.org/support/topic/if-your-lcp-posts-arent-ordering-properly-by-custom-fields-read-this/).

**Comment by ryuken** [comment]
ah thnx!
