### ISSUE TITLE
Custom Post Types Not Displaying By Tag

### ISSUE THREAD

**Issue by XSeabiscuitX** [picandocodigo/List-Category-Posts#336]
### Expected behavior
[catlist tags="example"] linking all posts with this tag, including custom post types.

### Actual behavior
Only displaying regular posts, excluding custom post types.

### Shortcode used and steps to reproduce the behavior
[catlist tags="example"]

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
Most Recent.

**Comment by zymeth25** [comment]
Have you read [the documentation](https://github.com/picandocodigo/List-Category-Posts/wiki/How-to-select-which-posts-to-show#other-ways-of-selecting-what-posts-to-show)?

> post_type - The type of post to show. Available options are: post - Default, page, attachment, any - all post types. You can use several types, example: [catlist post_type="page,post" numberposts=-1]

So your expected behavior is incorrect because `post` is the default value of the `post_type` parameter if you don't specify it yourself. To display any post types use `post_type=any`

**Comment by XSeabiscuitX** [comment]
So does it not work on custom post types? Even when I use "any" its only showing the regular posts and not the custom post types. I'm trying really hard to not be annoying but I'm new at this.




________________________________

**Comment by zymeth25** [comment]
What is the exact shortcode you tried after my first response?

**Comment by XSeabiscuitX** [comment]
Nevermind. I deactivated the plugin and reactivated it and now it's working! Thank you!


"It's kind of fun to do the impossible."



Chelsea


________________________________
