### ISSUE TITLE
PHP < 5.4 compatibility

### ISSUE THREAD

**Issue by zymeth25** [picandocodigo/List-Category-Posts#348]
In 0.76.1 we added a depracation warning for PHP < 5.4

In one of the recent PRs I wrote code that is incompatible with earler PHP versions. Now we have this:

https://wordpress.org/support/topic/update-caused-fatal-error/

https://wordpress.org/support/topic/new-version-0-79-issue-with-php-5-3/

We can either ignore that or change the line she mentioned: `[0]` to `array(0)`. Same change would have to be applied to line 86 of lcp-category.php

And also line 137 of lcp-catlist.php

Up to you.

(I would also change the PHP version requirement in the readme)

**Comment by picandocodigo** [comment]
Looking at the release history, 5.3 hasn't had a release since 2014 and 5.4 has been around since 2012. So I think it's fine to keep compatibility with 5.4 and up, if it's ok with you too.

WordPress suggests PHP version 7.2 or greater and it works with PHP 5.2.4+, but makes a note about it reaching the End Of Life. So if this encourages any user to update their servers from such an old version of PHP, we'll be helping make the web a better place :stuck_out_tongue: 

I updated the README to reflect this and if we decide it's worth supporting older versions of the plugin then we just need to make those changes and go back in the required version of PHP. But I'd argue it's probably better not to worry about supporting dead versions.

**Comment by zymeth25** [comment]
Yup, all agreed!
