### ISSUE TITLE
How to format a custom field date

### ISSUE THREAD

**Issue by redweatherday** [picandocodigo/List-Category-Posts#365]
Hi, I'm using an LCP shortcode with a custom field date in a text widget.

Having read the conversation re: #324
and 'Add filtering by customfield ranges' #328
and though I'm not a coder I managed to install the updated files and can confirm that it runs without error.

I'm using LCP to display some walks that occur a couple of weeks in the future and the above additions to custom fields returns exactly what I was looking to do.

This is my shortcode:
[catlist name=sunday-walks post_status=publish numberposts=3 customfield_date=walk_date customfield_after=today customfield_display=walk_date,walk_grade,walk_distance customfield_display_name=no customfield_display_separately=yes customfield_orderby=walk_date order=asc no_posts_text=To Be Announced]

My issue is how to format the date. My output is:

Wednesday Walk
20181128
Grade: Easy
Distance: 3.5 - 4.0 miles

but I would like the date to be Wednesday, 28th November 2018 (l, jS F Y).

I tried to follow this:
https://wordpress.org/support/topic/converting-custom-field-date-to-date-format/
I created a new template as per the documentation but am lost at where to insert the code into the template and how to display it in the text widget. Any help would be appreciated.

**Comment by zymeth25** [comment]
Hi

So going back to the thread where I originally explained how to do this, you need to put this code somewhere within the Loop (below `the_post();`):
```php
$date = get_post_meta( $post->ID, 'walk_date', true );
$dateTime = DateTime::createFromFormat("Ymd", $date);
```
(Use `Ymd` because it is the format your dates are saved in.)
It doesn't output anything, it just prepares the data for use later. 

Now you need to add the code that will output the formatted date. Insert this line just above the code that displays custom fields:
```php
$lcp_display_output .= $dateTime->format('l, jS F Y');
```

This whole procedure will 'manually' fetch and format the `walk_date` custom field, so you need to delete it from your `customfield_display` or it will be displayed again without formatting.

**Comment by zymeth25** [comment]
No problem!
You can close the issue.
