### ISSUE TITLE
Link underlines not appearing (or are white)

### ISSUE THREAD

**Issue by Larry-King** [picandocodigo/List-Category-Posts#367]
### Expected behavior
links produced by the shortcode in the sidebar should be "underlined" in a way that matches the rest of the WP theme I'm using (Twenty Seventeen). In this case, links should be underlined in black.

### Actual behavior
links are either not underlined at all, or perhaps they are underlined in white and just disappear against the white background.

### Shortcode used and steps to reproduce the behavior
I put this shortcode in a text widget in the sidebar:
[catlist name="Front Page Events" after=today numberposts=6  orderby=date order=asc date=yes]
The sidebar is displayed on the "home" page and all post pages at:
http://www.cslportland.org

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
Am using WP 5.0 and LCP plugin version 0.79

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by picandocodigo** [comment]
That's a CSS issue. The links are not underlined just like the links in your post headers. That's because the CSS in the theme is applying `text-decoration: none;` to some of the links (but not all of them). If you want them to show up underlined, you need to add `text-decoration: underline;` to the links in your widgets, or just the ones listed by LCP.

More info:
[Styling links](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links)
[text-decoration](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
