### ISSUE TITLE
Paginator suggestions

### ISSUE THREAD

**Issue by exie-czex** [picandocodigo/List-Category-Posts#385]
1. It would be great if paginator offered also first page and last page links as usual
<<  <   1  2  3  ...  10  >  >>

2. Could you add some tag (li) and class also to  '...'  so it could be styled accordingly

**Comment by picandocodigo** [comment]
Hello @exie-czex, thank you for your suggestions! I've just added a span and a class to `...`. So now it'll show:
```html
<span class='lcp_elipsis'>...</span>
```
I didn't want to add a `li` tag because that would change the current behaviour, but with this span you can style the elipsis however you prefer. Looking into adding first/last pages as an option (again, so I don't change the current behaviour).
