### ISSUE TITLE
Bug in lcp-catlistdisplayer.php?

### ISSUE THREAD

**Issue by hhenshaw** [picandocodigo/List-Category-Posts#399]
Line 181 of lcp-catlistdisplayer.php has a "=" operator rather than a ".=" operator.

### Expected behavior
Each list item displays the post fields as selected in the applicable template as per the HTML & CSS Customization documentation.

### Actual behavior
List item contents are preceded by an empty content item with the default tag and class provided by the template.

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
LCP 0.81

**Comment by picandocodigo** [comment]
@hhenshaw Thanks for reporting! We've been refactoring the code a lot, so this issue is not on the same line anymore. But I think this is the line you meant:

```php
    $lcp_display_output = '<'. $tag . ' ' . $tag_css . '>';
```
I believe this was ok? But that logic is changing with the following release so it will be different anyway. Let us know if you find any problems with the following version once the update is available. Cheers!
