### ISSUE TITLE
Column & Responsiveness 

### ISSUE THREAD

**Issue by kabirbd89** [picandocodigo/List-Category-Posts#421]
I tried to add css to list by column and also responsive with display sizes. Here the shortcode, 

`[catlist id=1 column_count=0 div_id="lcp_catlist"]`

And CSS are here, 

`@media only screen and (max-width: 500px) {
 #lcp_catlist {
  column-count:1;
  text-align:center
 }
}
@media only screen and (min-width: 501px) and (max-width: 1000px) {
 #lcp_catlist {
  column-count:2;
  margin-left: 20px;
  column-gap:20px
 }
}
@media only screen and (min-width: 1001px) {
 #lcp_catlist{
  column-count:3;
   margin-left: 20px; 
   column-gap:20px
 }
}`

It does not working, How can I show it in columns. I have been read twice html and css documentation, and I didn't figure out the solution. Its important to mentioned that i am not a pro person.

With Love, 
K

**Comment by zymeth25** [comment]
Hello @kabirbd89 

Are you sure you have read [this plugin's documentation](https://github.com/picandocodigo/List-Category-Posts/wiki)? Because the shortcode parameters you are using don't exist: there's no `column_count` or `div_id` so you can just remove them from your shortcode.

In your CSS, try replacing every `#lcp_catlist` with `#lcp_instance_0`.

**Comment by kabirbd89** [comment]
@zymeth25 
Thank you, its working.
