### ISSUE TITLE
Easily Change font/color

### ISSUE THREAD

**Issue by mrichey17** [picandocodigo/List-Category-Posts#437]
What a wonderful, accessible, easy solution to an very painful problem in Wordpress/Elementor. Thank you!

While this plugin makes it extremely easy to create category and/or post lists, it is extremely difficult to customize the appearance of those items (font type, size, color, delete/change bullet points). This is not possible for someone who does not know CSS or how to access the .php files through Wordpress' file structure. **Since List Category Posts is a widget anyway, I would like to request the feature to customize the font right there in the widget window or in the shortcode snippet itself without having to access the .php file or edit any CSS.** 

(This may not be feasible because of something I do not understand, and if that is the case then apologies for the request. I am very new to Wordpress.)

**Comment by picandocodigo** [comment]
Hi @mrichey17, thanks for your comments on the plugin! It's nice to know people find it helpful.

Unfortunately, changing the appearance of the styles in the widget would need a lot of work and complexity. We've been tending to avoid adding more stuff to the widget as it is and instead hoping users will take advantage of using the shortcode in a text/html widget instead. Even if we were to add this functionality, it'd be a separate add-on plugin to List Category Posts due to the complexity it would add.

We try to make it easy to customize as much as possible just using CSS (without the need to edit php files), and support the template system for more complex stuff. So right now the only solution is to use css for this.

**Comment by Konfekt** [comment]
For reference, this HTML (wrapping CSS) code changes the color of the unvisited links (`a:link`) in the unordered list (ul) of category posts to blue (`#0000ff`):

```html
<style>
ul.lcp_catlist
a:link {
  color: #0000ff;
}
</style>
```
