### ISSUE TITLE
jQuery pagination

### ISSUE THREAD

**Issue by picandocodigo** [picandocodigo/List-Category-Posts#64]
AJAX Pagination

**Comment by ierpe** [comment]
Hi, I started working on this feature, and I'm facing two problems :

*Problem number 1* is to keep/retrieve the attributes of the list we currently want the next/previous page from, since they're called with shortcodes / widgets and not stored in the database.

I was thinking about storing each list parameters into a session variable, with the instance number as the array indexes.

Something like :  
```
$_SESSION['lcp_lists'] = array(
0 => array(/* complete params */),
1 => array(/* complete params */),
/* etc... */
);
```

When an ajax call is triggered, we re-instanciate the list with its params and the wanted page for pagination, build the output, and send it back to the client.

====
*Problem number 2* is how do you define the HTML "container" that will be replaced with the ajax response, and all that should of course work with the templating system.

A solution I'm thinking about is to have the container and its id / classes becoming part of the list parameters. When the output of the list is not called with ajax, we add the container around the list, when the output is called with ajax, we do not include the container html, in order to be able to replace the container content on the site.

What do you think @picandocodigo ?

**Comment by picandocodigo** [comment]
@ierpe this is awesome, thanks!

I think using WP_Session would be the way to go yes. I don't have much time right now to look into this, but we probably need to store the instance id and identify the ajax lcp instance with that, then change the HTML in there with whatever comes from the plugin with or without a template.

Let me know if you have any further questions, I'll check it out if you submit a Pull Request.

**Comment by zymeth25** [comment]
I've been using the LCP plugin with Ajax pagination for half a year, I use this plugin:

https://github.com/malinky/malinky-ajax-pagination

This is why I added css classes to next pagination links because that plugin requires it to work. I think the way it works is good and we could mimic that behaviour in LCP. Relying on the Malinky plugin is something I've been hoping to get rid of so it would make my life easier. 

I could dedicate some time to this in Jan next year. What do you think @picandocodigo ?

**Comment by picandocodigo** [comment]
Hi @zymeth25, if it works with another plugin, I should add it to the README!

Thinking a bit more about this, it's probably better if we avoid loading more stuff, particularly JavaScript. But if it's possible to add it as an optional (without always adding any JS unless a parameter specifically asks for it), maybe it would be worth it. I'm thinking if this other plugin does this, maybe we can just make sure they're compatible with each other and suggest that? Let me know what you think.

**Comment by zymeth25** [comment]
@picandocodigo 
That plugin can change any 'classic' pagination into 1) simple Ajax pagination,  2) "infinite scroll"  3) a solution with a "load more" button.

By default the Ajax plugin loads it's JS and CSS (styles for the loader for "infinite scroll" and "load more" options) on every page. This is because the way it works is that in the backend you specify css selectors for the pagination you want the plugin to alter, then it puts those settings in a `<script>` before `</body>`. The JavaScript in `main.js` then takes these settings and traverses the html of every page, if it finds a match it does its magic. There are filters and class methods to easily control when the plugin's assets are loaded. So we could add a parameter that, if the Ajax plugin is installed and active, loads the assets, but it would then be impossible for users to use the Ajax plugin together with other paginated content if they wanted to...

I haven't tested this setup in different environments but it works with current version of LCP. With the exception of multiple paginations on same page (many instances of LCP): for this to work the Ajax plugin requires the posts' selector to be the parent of the navigation selector. In LCP this is not the case, the post list `<ul>` and the pagination `<ul>` are siblings. The only way to change it is custom code, which is what I did on one of my sites.

One problem I have with that plugin is that I'm not sure if it's maintained and how long until it stops working properly with current versions of WP. Last commit was 10 months ago. Another thing is that it's probably too robust a tool for a user who just wants to have cool Ajax pagination with LCP and nothing more, but I may be wrong here. So I'm with you on not loading stuff unless required by the shortcode and this is possible, what I was going to do some months ago (but I never got the time, i might have some soon though) was to fork the Ajax plugin and strip it off of everything that I don't need for the LCP integration.

Just have a look at that plugin when you have the time and let me know if you'd rather try something with it or do something else.

**Comment by picandocodigo** [comment]
@zymeth25 since this plugin hasn't been maintained since 2017, we shouldn't suggest it. I'm closing this issue and if we find a way to make this work with another plugin in the future, we can add it to the README. Otherwise if we were to implement something I think it should be a separate plugin.

**Comment by klemens-st** [comment]
Use this plugin.

https://wordpress.org/plugins/lcp-ajax-pagination/
