### ISSUE TITLE
Show only posts of the current category in the widget

### ISSUE THREAD

**Issue by picandocodigo** [picandocodigo/List-Category-Posts#69]
Show only posts of the current category in the widget, so it does not show posts if content is a page.

**Comment by zymeth25** [comment]
Aha, good that I've found this issue because I was wondering how to approach this. In #292 I did some fixes to current category handling and notied that there still is a problem of "what to do when there is no category detected". So following what you wrote here I'll continue work on `LcpCategory` class so that it doesn't return any posts in such cases. As of now we just get list of latest posts fromall categories.
